version: 2
dependencies:
  pre:
    - sudo apt-get update; sudo apt-get install libsystemd
jobs:
  build:
    docker:
      - image: rust:stretch
    steps:
      - checkout
      - run:
          name: Rust versions
          command: rustc --version && cargo --version
      - run:
          name: Cargo build
          command: cargo build --release
